image: docker:latest #베이스 이미지 버전

before_script: #Job 실행 전 우선 실행 스크립트
  - export 
stages: 
  - gradle-build #Job의 순서

gradle-build: 
  image: gradle:alpine 
  stage: gradle-build
  variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
  before_script: 
    - export GRADLE_USER_HOME=`pwd`/.gradle 
  script: 
    - gradle build 
  cache: 
    key: "$CI_COMMIT_REF_NAME" #Brunch 기준으로 캐싱
    paths: #캐싱할 대상들 
      - build 
      - .gradle 
  artifacts: #다음 Job으로 전달할 파일 또는 디렉토리
    paths: 
      - build/libs/*.jar 